# .github/workflows/build-cli-armv7.yml
name: Build CLI for Android ARMv7

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:  # امکان اجرای دستی

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: armv7-linux-androideabi
        override: true

    - name: Install Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
        unzip android-ndk-r26d-linux.zip
        echo "ANDROID_NDK_HOME=${{ github.workspace }}/android-ndk-r26d" >> $GITHUB_ENV
        echo "${{ github.workspace }}/android-ndk-r26d/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

    - name: Build for armv7
      run: |
        export ARMV7_LINUX_ANDROIDEABI_CC=armv7a-linux-androideabi21-clang
        cargo build --target armv7-linux-androideabi --release

    - name: Upload artifact (CLI)
      uses: actions/upload-artifact@v4
      with:
        name: il2cpp_dumper-cli-armv7
        path: target/armv7-linux-androideabi/release/il2cpp_dumper
